"""initial_schema_with_exam_marking

Revision ID: a69044576efe
Revises: 
Create Date: 2026-07-14 12:36:26.211595

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'a69044576efe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_tenant_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('classes_tenant_id_grade_section_academic_year_key'), 'classes', type_='unique')
    op.drop_index(op.f('idx_classes_tenant_id'), table_name='classes')
    op.create_index(op.f('ix_classes_tenant_id'), 'classes', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_class_per_tenant', 'classes', ['tenant_id', 'grade', 'section', 'academic_year'])
    op.drop_index(op.f('idx_periods_tenant_id'), table_name='periods')
    op.create_index(op.f('ix_periods_tenant_id'), 'periods', ['tenant_id'], unique=False)
    op.alter_column('pickup_requests', 'requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pickup_requests_class'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_parent'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_student'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_tenant'), table_name='pickup_requests')
    op.create_index(op.f('ix_pickup_requests_class_id'), 'pickup_requests', ['class_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_parent_id'), 'pickup_requests', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_student_id'), 'pickup_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_tenant_id'), 'pickup_requests', ['tenant_id'], unique=False)
    op.alter_column('social_mentions', 'topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('social_mentions', 'is_competitor',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('social_mentions', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_social_mentions_platform'), table_name='social_mentions')
    op.drop_index(op.f('idx_social_mentions_posted'), table_name='social_mentions')
    op.drop_index(op.f('idx_social_mentions_processed'), table_name='social_mentions')
    op.drop_index(op.f('idx_social_mentions_sentiment'), table_name='social_mentions')
    op.drop_index(op.f('idx_social_mentions_tenant'), table_name='social_mentions')
    op.create_index(op.f('ix_social_mentions_platform'), 'social_mentions', ['platform'], unique=False)
    op.create_index(op.f('ix_social_mentions_posted_at'), 'social_mentions', ['posted_at'], unique=False)
    op.create_index(op.f('ix_social_mentions_processed'), 'social_mentions', ['processed'], unique=False)
    op.create_index(op.f('ix_social_mentions_sentiment'), 'social_mentions', ['sentiment'], unique=False)
    op.create_index(op.f('ix_social_mentions_tenant_id'), 'social_mentions', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_students_tenant_id'), table_name='students')
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_subjects_tenant_id'), table_name='subjects')
    op.drop_constraint(op.f('subjects_tenant_id_code_key'), 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_subject_code_per_tenant', 'subjects', ['tenant_id', 'code'])
    op.alter_column('substitutions', 'confidence_reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_teachers_tenant_id'), table_name='teachers')
    op.drop_constraint(op.f('teachers_user_id_key'), 'teachers', type_='unique')
    op.create_index(op.f('ix_teachers_tenant_id'), 'teachers', ['tenant_id'], unique=False)
    op.create_unique_constraint(op.f('uq_teachers_user_id'), 'teachers', ['user_id'])
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'])
    op.alter_column('timetable_constraints', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_timetable_class_day'), table_name='timetable_entries')
    op.drop_index(op.f('idx_timetable_teacher_day'), table_name='timetable_entries')
    op.drop_index(op.f('idx_timetable_tenant_id'), table_name='timetable_entries')
    op.create_index(op.f('ix_timetable_entries_tenant_id'), 'timetable_entries', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_users_tenant_id'), table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index(op.f('idx_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_timetable_entries_tenant_id'), table_name='timetable_entries')
    op.create_index(op.f('idx_timetable_tenant_id'), 'timetable_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_timetable_teacher_day'), 'timetable_entries', ['teacher_id', 'day_of_week'], unique=False)
    op.create_index(op.f('idx_timetable_class_day'), 'timetable_entries', ['class_id', 'day_of_week'], unique=False)
    op.alter_column('timetable_constraints', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('uq_teachers_user_id'), 'teachers', type_='unique')
    op.drop_index(op.f('ix_teachers_tenant_id'), table_name='teachers')
    op.create_unique_constraint(op.f('teachers_user_id_key'), 'teachers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_teachers_tenant_id'), 'teachers', ['tenant_id'], unique=False)
    op.alter_column('substitutions', 'confidence_reasons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_subject_code_per_tenant', 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_tenant_id'), table_name='subjects')
    op.create_unique_constraint(op.f('subjects_tenant_id_code_key'), 'subjects', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_subjects_tenant_id'), 'subjects', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.create_index(op.f('idx_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_social_mentions_tenant_id'), table_name='social_mentions')
    op.drop_index(op.f('ix_social_mentions_sentiment'), table_name='social_mentions')
    op.drop_index(op.f('ix_social_mentions_processed'), table_name='social_mentions')
    op.drop_index(op.f('ix_social_mentions_posted_at'), table_name='social_mentions')
    op.drop_index(op.f('ix_social_mentions_platform'), table_name='social_mentions')
    op.create_index(op.f('idx_social_mentions_tenant'), 'social_mentions', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_social_mentions_sentiment'), 'social_mentions', ['sentiment'], unique=False)
    op.create_index(op.f('idx_social_mentions_processed'), 'social_mentions', ['processed'], unique=False)
    op.create_index(op.f('idx_social_mentions_posted'), 'social_mentions', ['posted_at'], unique=False)
    op.create_index(op.f('idx_social_mentions_platform'), 'social_mentions', ['platform'], unique=False)
    op.alter_column('social_mentions', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('social_mentions', 'is_competitor',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('social_mentions', 'topics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_pickup_requests_tenant_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_student_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_parent_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_class_id'), table_name='pickup_requests')
    op.create_index(op.f('ix_pickup_requests_tenant'), 'pickup_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_student'), 'pickup_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_parent'), 'pickup_requests', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_class'), 'pickup_requests', ['class_id'], unique=False)
    op.alter_column('pickup_requests', 'requested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_periods_tenant_id'), table_name='periods')
    op.create_index(op.f('idx_periods_tenant_id'), 'periods', ['tenant_id'], unique=False)
    op.drop_constraint('uq_class_per_tenant', 'classes', type_='unique')
    op.drop_index(op.f('ix_classes_tenant_id'), table_name='classes')
    op.create_index(op.f('idx_classes_tenant_id'), 'classes', ['tenant_id'], unique=False)
    op.create_unique_constraint(op.f('classes_tenant_id_grade_section_academic_year_key'), 'classes', ['tenant_id', 'grade', 'section', 'academic_year'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
